spring:
  application:
    name: lot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html